spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/futsalground?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 1234
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/futsalground
#    username: sa
#    password:

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show-sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
